### ISSUE TITLE
lua-physical.sty is missing

### ISSUE THREAD

**Issue by dbitouze** [tjenni/lua-physical#2]
Thanks for your nice package!

The basic preamble of the documentation contains:

```latex
\usepackage{lua-physical}
```
but, AFAICS, the `lua-physical.sty` file is missing both on CTAN (and then on TeX Live and on MiKTeX) and on the current GitHub repository.

**Comment by tjenni** [comment]
Hello dbitouze

Thank you. I know. The package doesn't work at the moment, because of path issues. I’m on it and will update it as soon as possible. The preamble `\usepackage{lua-physical}` and therefore the `lua-physical.sty` file will not be necessary. I’ll update the docs too.

**Comment by tjenni** [comment]
v1.0.2 should make it work. It should be out sync in 24h.
