### ISSUE TITLE
Spurious spaces when copy-paste from documentation

### ISSUE THREAD

**Issue by dbitouze** [tjenni/lua-physical#3]
When listings are copied-pasted from documentation, spurious spaces are added, e.g. before dashes, stars, commas, before or after quotes and after backslashes. For instance, with the Listing 1 (basic preamble) on page 3 and Listing 2 (Velocity of a car), we get:
```latex
\usepackage{lua -physical}
\usepackage{siunitx}
% configure siunitx
\sisetup{
output -decimal -marker = {.},
per -mode = symbol ,
separate -uncertainty = true ,
add -decimal -zero = true ,
exponent -product = \cdot ,
round -mode = off
}
% load the lua - physical package
\begin{luacode *}
physical = require (" physical ")
N = physical.Number
\end{luacode *}
% print a physical quantity
\newcommand {\q}[1]{%
\directlua{tex.print(physical.Quantity.tosiunitx (#1,"
scientific -notation=fixed ,exponent -to -prefix=false "))}
%
}
```
and
```latex
\begin{luacode}
s = 10 * _m
t = 2 * _s
v = s/t
\end{luacode}
A car travels $\q{s}$ in $\q{t}$. calculate its velocity.
$$
v=\ frac{s}{t} = \frac {\q{s}}{\q{t}} = \uuline {\q{v}}
$$
```

BTW, separating maths formulae from continuous text using `$$...$$` [is deprecated](http://mirrors.ctan.org/info/l2tabu/english/l2tabuen.pdf).

**Comment by tjenni** [comment]
The whitespaces do not occur on my system (os x). I did remove the line numbers in all listings and add `columns=flexible` to the listings configuration. Hopefully this will fix it.

**Comment by dbitouze** [comment]
Looks okay now.
