### ISSUE TITLE
Missing packages in basic preamble

### ISSUE THREAD

**Issue by dbitouze** [tjenni/lua-physical#4]
The basic preamble in the documentation is missing the following packages that are necessary for the various examples:

- `luacode` (for `luacode(*)` environments),
- `amsmath` (for `align(*)` environments),
- `ulem` (for `\uuline`).

I guess only `luacode` is mandatory for `lua-physical` and, IMHO, `ulem` may be more distracting than useful.

BTW:

1. if there isn't vertical alignment, the `equation(*)` environments are more appropriate than the `align(*)` ones (and don't require `amsmath`, even if the latter is more than advised when maths formula are involved),
1. when the following code is copied-pasted, the line break after `scientific-` leads to a compilation error:

```latex
\newcommand{\q}[1]{%
\directlua{tex.print(physical.Quantity.tosiunitx(#1,"scientific-
notation=fixed,exponent-to-prefix=false"))}%
}
```
I suggest it to be displayed as follows:
```latex
\newcommand{\q}[1]{%
  \directlua{
    tex.print(
    physical.Quantity.tosiunitx(
    #1,
    "scientific-notation=fixed,exponent-to-prefix=false"
    )
    )
  }%
}
```

**Comment by tjenni** [comment]
Thank you for your comment. I did update the docs and added more macros to the `basic preamble`. Is it now too complicated? Should I add more examples in the usage section to make it more clear?
