### ISSUE TITLE
Quantities interact with `nil` as dimensionless 1

### ISSUE THREAD

**Issue by bjornbm** [tjenni/lua-physical#5]
Examples:

```
> nil * _1
1 * _1
> nil + _1
2.0 * _1
> _1 - nil
0.0
> _m / nill
1.0 * _m
> _m / nil
1.0 * _m
> nil / _m
1.0 / _m
```

This had me tearing my hair for a while when I misspelled a variable name.

It seems to me that the problem is that `Quantity.new` does not check if its argument is `nil` at or before line 70:

```.lua
p.value = q or 1
```

Maybe the other constructors should also be tightened up?

**Comment by tjenni** [comment]
Thank you. What do you suggest? Should the constructor throw an error or return nil?

**Comment by bjornbm** [comment]
I think an error is the right approach.

**Comment by bjornbm** [comment]
After taking a look (and some minimal testing), I think the _easy_ change is to remove ` or 1` from line 78. This seems to provoke an error soon enough (whenever arithmetic is attempted).

Throwing an error requires more changes because of the pattern common in the code of calling `Quantity.new()` and assigning the `value` a few lines later. Maybe the easy option (above) is good enough. I will try it and see if I run into any obvious gotchas.

**Comment by tjenni** [comment]
I did change the code as you suggested. Thank you for reporting this issue.
